version: 0.0
os: linux
files:
  - source: /index.html
    destination: /usr/share/nginx/html/
hooks:
  BeforeInstall:
    - location: stop_server
      timeout: 300
      runas: root
  AfterInstall:
    - location: start_server
      timeout: 300
      runas: root
