version: 0.2
phases:
  install:
    commands:
      - yum -y update
      - yum -y install zip
      - yum -y install awscli
      - yum -y install git
  pre_build:
    commands:
      - aws s3 ls
  build:
    commands:
      - git clone https://github.com/sathavahanadevops/aws_codebuild_ngnix.git
      - cd aws_codebuild_ngnix
      - zip -r ngniz.zip aws_codebuild_ngnix
   post_build:
     commands:
       - aws s3 mv ngniz.zip s3://ngnixcodebuild
  artifacts:
     files:
       - ngniz.zip
