version: 0.2
phases:
  install:
    commands:
      - yum -y update
      - yum -y install zip
      - yum -y install awscli
      - yum -y install git
  pre_build:
    commands:
      - aws s3 ls
  build:
    commands:
      - echo build started
   post_build:
     commands:
       - aws s3 ls
  artifacts:
     files:
       - ngniz.zip
